name: backend
type: php:8.2

build:
    flavor: composer

relationships:
    database: "db:mysql"

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"

dependencies:
    php:
        extensions:
            - pdo
            - pdo_mysql
            - mysqli

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        composer install --no-dev --optimize-autoloader
    deploy: |
        php bin/console cache:clear
        php bin/console doctrine:migrations:migrate --no-interaction
