name: backend
type: php:8.2
disk: 1024  # Ajout pour éviter l'erreur

build:
    flavor: composer

relationships:
    database: "db:mysql"

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"

dependencies:
    php:
        extensions:
            - pdo
            - pdo_mysql
            - mysqli

mounts:
    "/var": { source: local, source_path: var }  # Ass
