security:
    # Configuration des algorithmes de hachage
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définition des providers (source des utilisateurs)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal pour l'API
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/security/login
                username_path: email
                password_path: password

        # Firewall principal pour les sessions (si nécessaire)
        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: /logout
            form_login:
                login_path: /login
                check_path: /login
            remember_me:
                secret: '%kernel.secret%'

    # Définition des contrôles d'accès
    access_control:
        - { path: ^/api/security/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/security/account/me, roles: ROLE_USER }
        - { path: ^/api/security/account/edit, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
