name: front
type: nodejs:16 # Version de Node.js
web:
  locations:
    "/":
      root: "build" # Dossier contenant les fichiers buildés (par exemple pour React ou Angular)
      index: "index.html"
build:
  commands:
    - npm install
    - npm run build
disk: 512
