name: front
type: nodejs:16 # Version de Node.js
web:
  locations:
    "/":
      root: "build" # Dossier contenant les fichiers buildés (par exemple pour React ou Angular)
      index: "index.html"
build:
  flavor: none
  commands:
    build: |
      npm install
      npm run build
disk: 512
